# Generated by Django 4.0.3 on 2022-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_systemchatlogs_userchatlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlogs',
            name='filled_quantity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='oms_order_id',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='order_status',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='price',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='product',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='quantity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='rejection_reason',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='chatlogs',
            name='symbol',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='filled_quantity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='oms_order_id',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='order_status',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='price',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='product',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='quantity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='rejection_reason',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='symbol',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='filled_quantity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='oms_order_id',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='order_status',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='price',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='product',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='quantity',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='rejection_reason',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='symbol',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
