# Generated by Django 4.0.3 on 2022-04-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatlogs_filled_quantity_chatlogs_oms_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlogs',
            name='type',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='systemchatlogs',
            name='type',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='userchatlogs',
            name='type',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
